---
abstract: 'A no-frills converter between 1D and 2D spaces using the Hilbert curve'
author:
  - "\"PWBENNETT\" <paul.w.bennett@gmail.com>"
build_requires:
  ExtUtils::MakeMaker: 0
  Test::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Hilbert
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Math::BigInt: 0
  integer: 0
  local::lib: 0
  perl: 5.012
version: 1.202
